### ISSUE TITLE
Read.me instructions unclear

### ISSUE THREAD

**Issue by jazzymcgee** [IBM/vr-speech-sandbox-cardboard#52]
Cloned repositories exactly to instructions, however, no such directory called Creation Sandbox exists within any folder. Could you clarify please? Thanks (Example of Read.me instructions below)

```
Open Unity and inside the project launcher select the Open button.
Navigate to where you cloned this repository and open the Creation Sandbox directory.
```

**Comment by scottdangelo** [comment]
That should be `SpeechSandbox` directory.
This is fixed with `commit 179c50fb1a7`
