### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by syedzainn** [IBM/vr-speech-sandbox-cardboard#53]
Hi,
I am getting this error : [Credentials.OnGetTokenFail();][DEBUG] Failed to get IAM Token: URL: https://stream.watsonplatform.net/speech-to-text/api, ErrorCode: 401, Error: Generic/unknown HTTP error, Response: {"code":401, "error": "Unauthorized"}
Please help.
Thank you

**Comment by scottdangelo** [comment]
I have reproduced an auth error, although it is a 400. I'll continue to investigate.

**Comment by scottdangelo** [comment]
I was able to get the application working. Here are the steps.
1. I re-created both the Speech-to-text and the Watson Assistant services
2. I deleted the entire repository, and re-cloned it. I also re-cloned the unity-sdk into `SpeechSandbox/Assets/`
3. I started the app in Unity 2018.3.0f2
4. I put in my IAM apikey and service URL (https://stream.watsonplatform.net/speech-to-text/api) for Speech-to-Text
5. I put in my IAM apikey, workspace ID, service URL (https://gateway.watsonplatform.net/assistant/api) and today's date (2018-02-11) for `Assistant Version Date`.

<img width="360" alt="workingcreds" src="https://user-images.githubusercontent.com/14651388/52588386-97e53b80-2df9-11e9-8678-82678f416a20.png">

6. I made sure File->Build Settings was set to `Android` (See [Troubleshooting](https://github.com/IBM/vr-speech-sandbox-cardboard#troubleshooting)
7. I started the app with `Run` and it worked.

Please let me know if you can get it working using these instructions.

**Comment by jwombat** [comment]
(Sorry for the delay, been pretty sick.)

YES!

Thank you ! I've created lots of balls and boxes. Now to get it into my app.

For the record, Unity 2018.3.5f1

**Comment by syedzainn** [comment]
Hi, It works finally!

**Comment by stevemart** [comment]
thanks @scottdangelo !
