### ISSUE TITLE
authentication error, moved from Watson-Unity-ARKit

### ISSUE THREAD

**Issue by jwombat** [IBM/vr-speech-sandbox-cardboard#55]
(appears to be related to #53)

Did you get a chance to look at this?

As I mentioned, one thing that's confusing is that I can successfully get a request handled if I issue it using curl. Checking the request that's being issued by the Unity package, I don't see that my authentication is in the request; could that explain why I always get a 401:Unauthorized?

**Comment by scottdangelo** [comment]
I have reproduced an auth error, although it is a 400. I'll continue to investigate.

**Comment by scottdangelo** [comment]
I've responded with my findings in #53

**Comment by scottdangelo** [comment]
@jwombat can you please try with the workaround in #53 ?

**Comment by scottdangelo** [comment]
Workaround has been posted in #53 . I am closing this issue.
