### ISSUE TITLE
new prefabs addition error

### ISSUE THREAD

**Issue by sidd-gupta** [IBM/vr-speech-sandbox-cardboard#58]
I am trying to add new prefabs (or objects). I added intent and entities in the IBM cloud and also in
the assets folder. But I am getting the error KeyNotFoundException.
Can you please tell me the changes in the code to add new prefabs.
![Screenshot (21)](https://user-images.githubusercontent.com/33632155/54452932-3c052e00-477c-11e9-89f1-a4dc8da98d61.png)

**Comment by sidd-gupta** [comment]
@scottdangelo Can you please help me out with this?

**Comment by scottdangelo** [comment]
Sorry, but that is beyond the scope of this code pattern. You will need to do some research on [Unity Prefabs](https://docs.unity3d.com/Manual/Prefabs.html). You can look in the Unity editor at the keys/values in the scene where the existing prefabs are, and get some clues as to how to modify for your purposes.
